name: Android CI/CD

on:
  push:
    branches:
      - main  # Jalankan ketika ada push ke branch main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      # Step 3: Grant permission to execute gradlew
      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      # Step 4: Build APK (Debug)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Run Unit Tests (opsional, bisa dihapus kalau belum perlu)
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 6: Simpan APK sebagai artifact
      - name: Save APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
